/*
 * Cart Purchase Microservice
 * Cart purchase microservice
 *
 * OpenAPI spec version: 1.0.0
 * Contact: satoshikisaki@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.cartpurchase.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

/**
 * Item
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-17T21:51:11.721328500-03:00[America/Sao_Paulo]")
public class Item {

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("productTitle")
  private String productTitleItem = null;

  @JsonProperty("description")
  private String descriptionItem = null;

  @JsonProperty("brandName")
  private String brandNameItem = null;

  @JsonProperty("material")
  private String materialItem = null;

  @JsonProperty("color")
  private String colorItem = null;

  @JsonProperty("quantity")
  private Integer quantityItem = null;

  @JsonProperty("dimensions")
  private Dimensions dimensionsItem = null;

  @JsonProperty("price")
  private BigDecimal priceItem = null;

  /**
  * Get id
  * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  /**
  * Get productTitle
  * @return productTitle
  **/
  @Schema(example = "Water Bottle 1L", description = "")
  public String getProductTitle() {
    return productTitleItem;
  }

  public void setProductTitle(String productTitle) {
    this.productTitleItem = productTitle;
  }

  /**
  * Get description
  * @return description
  **/
  @Schema(example = "The portable water can be used in various occasions. The gym, camping, traveling, as well as in the office and at home.", description = "")
  public String getDescription() {
    return descriptionItem;
  }

  public void setDescription(String description) {
    this.descriptionItem = description;
  }

  /**
  * Get brandName
  * @return brandName
  **/
  @Schema(example = "Xiaomi", description = "")
  public String getBrandName() {
    return brandNameItem;
  }

  public void setBrandName(String brandName) {
    this.brandNameItem = brandName;
  }

  /**
  * Get material
  * @return material
  **/
  @Schema(example = "Plastic", description = "")
  public String getMaterial() {
    return materialItem;
  }

  public void setMaterial(String material) {
    this.materialItem = material;
  }

  /**
  * Get color
  * @return color
  **/
  @Schema(example = "Red", description = "")
  public String getColor() {
    return colorItem;
  }

  public void setColor(String color) {
    this.colorItem = color;
  }

  /**
  * Get quantity
  * @return quantity
  **/
  @Schema(example = "1", description = "")
  public Integer getQuantity() {
    return quantityItem;
  }

  public void setQuantity(Integer quantity) {
    this.quantityItem = quantity;
  }

  /**
  * Get dimensions
  * @return dimensions
  **/
  @Schema(description = "")
  public Dimensions getDimensions() {
    if(dimensionsItem == null) {
      dimensionsItem = new Dimensions();
    }
    return dimensionsItem;
  }

  public void setDimensions(Dimensions dimensions) {
    this.dimensionsItem = dimensions;
  }

  /**
  * Get price
  * @return price
  **/
  @Schema(example = "9.99", description = "")
  public BigDecimal getPrice() {
    return priceItem;
  }

  public void setPrice(BigDecimal price) {
    this.priceItem = price;
  }


}
